# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            C&L
tagline:          'A simple blog'
description:      Wing Gao's blog<br><a href="https://twitter.com/Wing_Gao">@Wing_Gao</a>
url:              http://blog.wingao.me

author:
  name:           'Wing Gao'
  url:            https://twitter.com/Wing_Gao

paginate:         5

github:
  repo:           https://github.com/WingGao/me
